mobile version updated
dhy-612/portfolio pull request #4
Opened 2023-01-15 04:05 UTC by dhy-612

Milestone 2 
Completed a basic structure of the mobile version of the portfolio

2023-01-15 06:03 UTC, NahnahAJ requested changes
Hi @dhy-612 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Good commit messages :heavy_check_mark: 
- Professional README :heavy_check_mark: 
- No linter errors :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Writing a more detailed pull request next time :+1: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-15 06:03 UTC, NahnahAJ commented on styles.css
> +  flex-grow: 0; */
- Kindly avoid leaving commented pieces of code in your project. It is unprofessional and makes your code unclean. :+1:

2023-01-15 06:03 UTC, NahnahAJ commented on styles.css
>    order: 0;
- Kindly avoid leaving commented pieces of code in your project. It is unprofessional and makes your code unclean. :+1:

2023-01-15 06:03 UTC, NahnahAJ commented on styles.css
> +  height: 409px; */
- Kindly avoid leaving commented pieces of code in your project. It is unprofessional and makes your code unclean. :+1:

2023-01-17 00:20 UTC, Yerimah requested changes
# STATUS: REQUESTED CHANGES 🔴 

Hi @dhy-612, 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b70556d45436b5038554458344c37536b552f67697068792e676966](https://user-images.githubusercontent.com/71140133/212782935-07da2bd2-b080-43ae-b8b8-b21ca674094f.gif)

## Highlights
- No linter error ✔️ 
- GitHub flow used ✔️ 
- Descriptive PR title and summary ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 00:20 UTC, Yerimah commented on styles.css
>    order: 0;
- I would encourage you to always implement changes made by a reviewer before requesting another review. Kindly make these changes before submitting for review. 🙏

2023-01-19 19:58 UTC, NahnahAJ approved these changes
Hi @dhy-612 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>
## Highlights
- Good use of GitHub flow :heavy_check_mark: 
- Good commit messages :heavy_check_mark:
- Professional README :heavy_check_mark:
- No linter errors :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 20:03 UTC, merged